- name: Add nova flavors
  os_nova_flavor:
    name: '{{ item.name }}'
    ram: '{{ item.ram | int }}'
    disk: '{{ item.disk | int }}'
    vcpus: '{{ item.vcpus | int }}'
    flavorid: '{{ item.flavorid | default(omit) }}'
    rxtx_factor: '{{ item.rxtx_factor | default(omit) }}'
    ephemeral: '{{ item.ephemeral | default(omit) }}'
    is_public: '{{ item.is_public | default(omit) }}'
    swap: '{{ item.swap | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
    auth:
      auth_url: "{{ endpoints.auth_uri  }}"
      project_name: admin
      username: admin
      password: "{{ secrets.admin_password  }}"
  with_items: '{{ nova.flavors | default([]) }}'
  run_once: true
